Fix methods that access empty DOM structures
IngressoRapidoWebComponents/unknown-carousel pull request #3
Opened 2019-05-22 17:00 UTC by yanmagalhaes-ir

# Solution
 - Check methods that uses DOM nodes and prev check your selection

2019-05-22 20:48 UTC, lucas-oliveira-sympla approved these changes

2019-05-23 13:47 UTC, daniele-ivasse reviewed
@yanmagalhaes-ir conforme eu comentei em um PR anterior seu, todas as checagens que vc fez, a leitura do código fica mais intuitiva se removermos o `!!`. Se tratasse de um retorno que deveríamos garantir que fosse `true` ou `false` e evitar um  `undefined`, o `!!` faria sentido.

2019-05-23 14:38 UTC, leticia-p approved these changes

2019-05-27 14:06 UTC, andrewillard requested changes

2019-05-27 14:06 UTC, andrew-silva-movile commented on unknown-carousel.html
> +            if(!!n) {
```suggestion
            if(n) {
```
O próprio JS resolve isso pra você, aqui você terá perca de performance como discutimos e foi comparado pelo Will

2019-05-27 14:06 UTC, andrew-silva-movile commented on unknown-carousel.html
> +            s = !!r ? r.children : [],
```suggestion
            s = r ? r.children : [],
```

2019-05-27 14:06 UTC, andrew-silva-movile commented on unknown-carousel.html
> +            o = !!e ? e.style.transform : '',
```suggestion
            o = e ? e.style.transform : '',
```

2019-05-27 14:06 UTC, andrew-silva-movile commented on unknown-carousel.html
> +            l = (this.items() - (!!this.getPages()[t] ? this.getPages()[t].length : 0)) * e,
```suggestion
            l = (this.items() - (this.getPages()[t] ? this.getPages()[t].length : 0)) * e,
```

2019-05-27 14:06 UTC, andrew-silva-movile commented on unknown-carousel.html
> +            h = (this.items() - (!!this.getPages()[t] ? this.getPages()[t].length : 0)) * o,
```suggestion
            h = (this.items() - (this.getPages()[t] ? this.getPages()[t].length : 0)) * o,
```

2019-05-27 14:06 UTC, andrew-silva-movile commented on unknown-carousel.html
> +            l = !!a ? a.children : [],
```suggestion
            l = a ? a.children : [],
```

2019-05-27 14:06 UTC, andrew-silva-movile commented on unknown-carousel.html
> +          return !!a ? a.style.minWidth = o + "px" : null
```suggestion
          return a ? a.style.minWidth = o + "px" : null
```

2019-05-27 14:06 UTC, andrew-silva-movile commented on unknown-carousel.html
> +            !!e ? e.style.touchAction = "" : null
```suggestion
            e ? e.style.touchAction = "" : null
```

2019-05-27 14:06 UTC, andrew-silva-movile commented on unknown-carousel.html
> +            !!e ? e.style.transition = "none" : null,
```suggestion
            e ? e.style.transition = "none" : null,
```

2019-05-27 14:06 UTC, andrew-silva-movile commented on unknown-carousel.html
> +            !!e ? e.style.transition = "" : null,
```suggestion
            e ? e.style.transition = "" : null,
```

2019-05-27 17:42 UTC, yanmagalhaes-ir commented
@andrew-silva-movile @daniele-ivasse atualizado

2019-05-27 17:43 UTC, andrewillard approved these changes

2019-05-27 19:50 UTC, merged