[BF-29] Fix navigation action in carousel
IngressoRapidoWebComponents/unknown-carousel pull request #4
Opened 2019-06-11 22:13 UTC by yanmagalhaes-ir

[Task](https://sympla.atlassian.net/browse/BF-29)  

# Solution

- Use `parentElement` to get elements for make transition

2019-06-12 01:59 UTC, daniele-ivasse requested changes

2019-06-12 01:59 UTC, daniele-ivasse commented on unknown-carousel.html
> +              debugger;
Remover

2019-06-12 01:59 UTC, daniele-ivasse commented on unknown-carousel.html
>              e = this._isLoop ? Math.round(100 / this._getRealTotalItems() * 1e4) / 1e4 : Math.round(100 / this.getTotalItems() * 1e4) / 1e4,
@yanmagalhaes-ir na linha abaixo (469) vc precisa alterar para:
`l = s.parentElement.querySelectorAll('div.box-wrapper') || [];`
Do jeito que está, ele não está calculando a largura de cada item em porcentagem, ficando um espaço maior entre as datas. Eu testei dessa maneira acima e funcionou.

2019-06-12 02:53 UTC, yanmagalhaes-ir commented on unknown-carousel.html
>              e = this._isLoop ? Math.round(100 / this._getRealTotalItems() * 1e4) / 1e4 : Math.round(100 / this.getTotalItems() * 1e4) / 1e4,
Ok @daniele-ivasse , alterado

2019-06-12 02:53 UTC, yanmagalhaes-ir commented on unknown-carousel.html
> +              debugger;
Erro meu ter deixado .... alterado

2019-06-12 13:37 UTC, leticia-p approved these changes

2019-06-12 13:47 UTC, andrew-silva-movile commented on unknown-carousel.html
> +            n = s.shadowRoot.querySelector(".unknown-carousel_wrapper"),
@yanmagalhaes-ir vamos usar o Polymer.dom assim fica compatível com o hibrido.

2019-06-12 13:47 UTC, andrew-silva-movile commented on unknown-carousel.html
> +            for (a = s.parentElement.querySelectorAll('div.box-wrapper'),
@yanmagalhaes-ir pior que o "box-wrapper" não é mesmo do carousel é do event offers, lembra que isso era uma duvida nossa? Se usar esse selector na IR vai dar problema. Tem como ficar compatível?

2019-06-12 13:47 UTC, andrew-silva-movile commented on unknown-carousel.html
> +              for (l = s.parentElement.querySelectorAll('div.box-wrapper'),
mesmo ponto acima

2019-06-12 13:47 UTC, andrew-silva-movile commented on unknown-carousel.html
> +            r = i.shadowRoot.querySelector(".unknown-carousel_wrapper"),
mesmo ponto do polymer.dom

2019-06-12 13:47 UTC, andrew-silva-movile commented on unknown-carousel.html
> +            s = r ? i.parentElement.querySelectorAll('div.box-wrapper') : [],
mesmo ponto da classe css

2019-06-12 13:47 UTC, andrew-silva-movile commented on unknown-carousel.html
> +            e = t.shadowRoot.querySelector(".unknown-carousel_wrapper"),
mesmo ponto do polymer.dom

2019-06-12 13:47 UTC, andrew-silva-movile commented on unknown-carousel.html
> +            i = o.shadowRoot.querySelector(".unknown-carousel_wrapper"),
mesmo ponto do polymer.dom

2019-06-12 13:47 UTC, andrew-silva-movile commented on unknown-carousel.html
> +            i = o.shadowRoot.querySelector(".unknown-carousel_wrapper"),
mesmo ponto do polymer.dom

2019-06-12 13:47 UTC, andrew-silva-movile commented on unknown-carousel.html
> +            r = i.shadowRoot.querySelector(".unknown-carousel_wrapper"),
mesmo ponto do polymer.dom

2019-06-12 13:47 UTC, andrew-silva-movile commented on unknown-carousel.html
> +            a = s.shadowRoot.querySelector(".unknown-carousel_wrapper"),
mesmo ponto do polymer.dom

2019-06-12 13:47 UTC, andrew-silva-movile commented on unknown-carousel.html
> +            e = t.shadowRoot.querySelector(".unknown-carousel_wrapper"),
mesmo ponto do polymer.dom

2019-06-12 13:47 UTC, andrew-silva-movile commented on unknown-carousel.html
> +            e = t.shadowRoot.querySelector(".unknown-carousel_wrapper"),
mesmo ponto do polymer.dom

2019-06-12 13:47 UTC, andrew-silva-movile commented on unknown-carousel.html
> +            return i = o.shadowRoot.querySelector(".unknown-carousel_wrapper"),
mesmo ponto do polymer.dom

2019-06-12 13:47 UTC, andrew-silva-movile commented on unknown-carousel.html
> +          c = u.shadowRoot.querySelector(".unknown-carousel_wrapper"),
mesmo ponto do polymer.dom

2019-06-12 13:47 UTC, andrew-silva-movile commented on unknown-carousel.html
> +            l = a ? s.parentElement.querySelectorAll('div.box-wrapper') || [] : [],
mesmo ponto da classe css

2019-06-12 13:57 UTC, lcassiano1612 commented
@yanmagalhaes-ir o primeiro item do carrosel não esta exibindo um detalhe de borda
![image](https://user-images.githubusercontent.com/29260162/59357151-b18f8480-8d00-11e9-99bc-1ab26e6138fa.png)

2019-06-12 14:00 UTC, daniele-ivasse commented on unknown-carousel.html
> +            for (a = s.parentElement.querySelectorAll('div.box-wrapper'),
@yanmagalhaes-ir deve funcionar:
`Polymer.dom(s).querySelectorAll('.unknown-carousel_wrapper > div')`

2019-06-12 14:00 UTC, daniele-ivasse commented on unknown-carousel.html
> +              for (l = s.parentElement.querySelectorAll('div.box-wrapper'),
@yanmagalhaes-ir deve funcionar:
`Polymer.dom(s).querySelectorAll('.unknown-carousel_wrapper > div')`

2019-06-12 14:00 UTC, daniele-ivasse commented on unknown-carousel.html
> +            s = r ? i.parentElement.querySelectorAll('div.box-wrapper') : [],
@yanmagalhaes-ir deve funcionar:
`Polymer.dom(s).querySelectorAll('.unknown-carousel_wrapper > div')`

2019-06-12 15:19 UTC, yanmagalhaes-sympla commented
@lcassiano1612 hoje ele já está desta forma, tanto em `homolog` como `prod`

2019-06-12 17:57 UTC, lucas-oliveira-sympla approved these changes

2019-06-12 22:08 UTC, daniele-ivasse approved these changes

2019-06-13 18:20 UTC, andrewillard approved these changes

2019-06-13 21:03 UTC, merged